name = "network"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "95b97205-aec4-4ce4-a0a5-6b37e6ff1d62"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
